@startuml C4-Modell-Level2
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Container(ColorClicker, "ColorClicker", "the customer wants to play a Game, where he can invest a lot of time")
Container(database, "Database", "Game", "the color clicker tries that the player of this game invests a lot of money and time in the game")
Person(player, "User", "has a username and a password")
Container(webApplication, "WebApplication", "user can play the game as a web application and doesnt have to download any files for it")
Container(mobileApplication, "MobileApplication", "user can download the game in any store")

Rel(player, database, "Saving and Acessing Data", "the username of every player will be saved in the database with the personal informations")
Rel(ColorClicker, database, "Saving and Acessing Data")
Rel(player,ColorClicker, "User plays the game")
Rel(ColorClicker,webApplication, "Game as WebApplication")
Rel(ColorClicker,mobileApplication, "Game as WebApplication")

@enduml